version: '{build}'
skip_branch_with_pr: true
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
build_script:
- ps: .\build.ps1 -Target "CI" -Configuration "Release"
test: off
artifacts:
- path: artifacts\*.nupkg